// Team member data for RICCC and RHEDAS labs
import { type InsertTeamMember } from "@shared/schema";

type TeamMemberData = Omit<InsertTeamMember, 'id' | 'createdAt' | 'updatedAt' | 'labId' | 'initials' | 'position'>;

export const RICCC_TEAM_MEMBERS: TeamMemberData[] = [
  {
    name: "Kevin Buell",
    email: "Kevin_Buell@rush.edu",
    role: "PI",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Juan Rojas",
    email: "juan_rojas@rush.edu", 
    role: "PI",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC & RHEDAS",
    startDate: new Date(),
  },
  {
    name: "Hoda Masteri",
    email: "Hoda_MasteriFarahani@rush.edu",
    role: "Data Scientist",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Vaishvik Chaudhari",
    email: "Vaishvik_Chaudhari@rush.edu",
    role: "Data Scientist", 
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Jonathan Tsai",
    email: "Chuan-Ching_Tsai@rush.edu",
    role: "Data Scientist",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Mia Mcclintic",
    email: "Mia_R_McClintic@rush.edu",
    role: "Regulatory Coordinator",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Connor P Lafeber",
    email: "Connor_P_Lafeber@rush.edu",
    role: "Lab Intern",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Dariush Mokhlesi",
    email: "dariushmokhlesi@gmail.com",
    role: "Summer Intern",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Kian Mokhlesi",
    email: "kianmokhlesi@gmail.com",
    role: "Summer Intern",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
  {
    name: "Elijah John",
    email: "Elijah_John@rush.edu",
    role: "Summer Intern",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC",
    startDate: new Date(),
  },
];

export const RHEDAS_TEAM_MEMBERS: TeamMemberData[] = [
  {
    name: "Juan Rojas",
    email: "juan_rojas@rush.edu",
    role: "PI", 
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RICCC & RHEDAS",
    startDate: new Date(),
  },
  {
    name: "Jason Stanghelle",
    email: "Jason_Stanghelle@rush.edu",
    role: "Data Scientist",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RHEDAS",
    startDate: new Date(),
  },
  {
    name: "Meher Sapna Masanpally",
    email: "MeherSapna_Masanpally@rush.edu",
    role: "Data Analyst",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RHEDAS",
    startDate: new Date(),
  },
  {
    name: "Jada Sherrod",
    email: "Jada_J_Sherrod@rush.edu",
    role: "Coordinator",
    isActive: true,
    avatarUrl: null,
    phoneNumber: null,
    department: "RHEDAS",
    startDate: new Date(),
  },
];